version: "3"

services: 
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets/e47b709b-5c82-4a61-935c-823e332955f9/:/root/.microsoft/usersecrets/e47b709b-5c82-4a61-935c-823e332955f9/